---
#persistentVolumeClaim for the file data store
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prevayler-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
