FROM nginx:1.19.6
COPY artifacts/site.zip /usr/share/nginx/html
RUN apt-get update && apt-get install -y unzip
RUN rm /etc/nginx/conf.d/default.conf && \
    unzip -o /usr/share/nginx/html/site.zip -d /usr/share/nginx/html/ && \
    rm /usr/share/nginx/html/site.zip
